AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Run cost comparison of AutoScalr to Spot Fleet
Parameters:
  InstanceTypes:
    Type: String
    Default: m4.large,m4.xlarge,c4.large,c4.xlarge,r4.large,r4.xlarge
    Description: >
      Comman delimited EC2 instance types to use in Spot Fleet and AutoScalr
    Description: Instance types to use in Spot Fleet and AutoScalr
  TargetVCpuSize:
    Type: Number
    Default: 1
    Description: >
      Target vCPU size to run both Spot Fleet and AutoScalr at for test
  TestDuration:
    Type: Number
    Default: 1
    Description: >
      Hours to run test
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: amKeyPair
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
Mappings:
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-6869aa05
    us-east-2:
      AMIID: ami-f6035893
    us-west-1:
      AMIID: ami-31490d51
    us-west-2:
      AMIID: ami-7172b611
    eu-west-1:
      AMIID: ami-f9dd458a
    eu-west-2:
      AMIID: ami-886369ec
    eu-central-1:
      AMIID: ami-ea26ce85
    ap-northeast-1:
      AMIID: ami-374db956
    ap-northeast-2:
      AMIID: ami-2b408b45
    ap-southeast-1:
      AMIID: ami-a59b49c6
    ap-southeast-2:
      AMIID: ami-dc361ebf
    ap-south-1:
      AMIID: ami-ffbdd790
    sa-east-1:
      AMIID: ami-6dd04501
    ca-central-1:
      AMIID: ami-730ebd17
Resources:
  AutoScalrFleetBenchmark:
    Type: AWS::S3::Bucket
  MgrSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security Group for AutoScalr Benchmark Manager
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  AutoScalrFleetBenchmarkMgrInst:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref 'KeyName'
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID]
      SecurityGroups:
        - !Ref 'MgrSecurityGroup'
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum -y install git
              yum -y install nodejs npm --enablerepo=epel
              wget https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
              tar -C /usr/local -xzf go*.gz
              export PATH=$PATH:/usr/local/go/bin
              wget https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip
              unzip terraform*.zip
              mv terraform /usr/local/bin
              echo export ASR_TEST_DURATION=${TestDuration} >> /home/ec2-user/testRun.env
              echo export ASR_TARG_VCPU=${TargetVCpuSize} >> /home/ec2-user/testRun.env
              echo export ASR_INST_TYPES=${InstanceTypes} >> /home/ec2-user/testRun.env
              echo export ASR_TEST_AMI=${TestAmi} >> /home/ec2-user/testRun.env
              sudo -u ec2-user bash -c "cd;git clone https://github.com/autoscalr/fleet-cost-benchmark.git"
              sudo -u ec2-user bash -c "~/fleet-cost-benchmark/scripts/runBenchmark.sh"
            - {
                TestAmi: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID]
              }

Outputs:
  S3ResultsBucket:
    Value: !Ref 'AutoScalrFleetBenchmark'
